### PR TITLE
Support conversion between ed25519 and sr25519 formats for private key

### PR DESCRIPTION
**Pull request by ERussel**
To be compatible with https://polkadot.js.org/apps and corresponding web extension we need an option to export/import sr25519 private key in ed25519 format otherwise key generated by the library can't be imported to the polkadot.js and vice verse. Here is how they processes the raw bytes of the [key](https://github.com/polkadot-js/wasm/blob/master/packages/wasm-crypto/src/rs/sr25519.rs#L115).

Here is the reference implementation I used for [from_ed25519](https://github.com/w3f/schnorrkel/blob/master/src/keys.rs#L510) and [to_ed25519](https://github.com/w3f/schnorrkel/blob/master/src/keys.rs#L475).

As we now have additional logic for the private key it was decided to place it in the separate model. Keypair model is also refactored to use new private key model instead of raw bytes.

### CODE REVIEW

**Comment by ypopovych** [comment]
Thank you! I will check tomorrow and merge if everything is ok

**Comment by ypopovych** [comment]
Hi. I found this in documentation in sr25519-donna:
```
By default, the sr25519_keypair_from_seed functon creates keypair that contains
half ed25519 bytes (which is compatible with the wasm crypto lib), 
vrf requires the keypair is uniform. In this case, you can use 
sr25519_uniform_keypair_from_seed for keypair creating or
sr25519_keypair_ed25519_to_uniform for converting. 
```
Have you checked the default key format? Because this C library works in a different way than Rust one

**Comment by ERussel** [comment]
> Hi. I found this in documentation in sr25519-donna:
> 
> ```
> By default, the sr25519_keypair_from_seed functon creates keypair that contains
> half ed25519 bytes (which is compatible with the wasm crypto lib), 
> vrf requires the keypair is uniform. In this case, you can use 
> sr25519_uniform_keypair_from_seed for keypair creating or
> sr25519_keypair_ed25519_to_uniform for converting. 
> ```
> 
> Have you checked the default key format? Because this C library works in a different way than Rust one

Hey! I didn't expect that C implementation is using different format for private key. Now I run the compatibility test using test vectors from this [one](https://github.com/ERussel/IrohaCrypto/blob/master/Tests/SR25519/SNKeyFactoryTests.m#L33) that uses bindings to rust implementation and can see that it is really different. Public keys are matching (as expected) but private keys don't. So It is neither compatible with default rust implementation nor with ed25519 format. So it is third one! I will work more on this PR later. Thank you!

**Comment by ERussel** [comment]
Finally, I understood that `sr25519_keypair_from_seed` is compatible with polkadot.js and `sr25519_uniform_keypair_from_seed` is compatible with rust implementation. Also we have `sr25519_keypair_ed25519_to_uniform` to convert to uniform but not other way around. The most strange thing is absence of `key[31] &= 0b01111111;` operation which present in reference implementation and as I understand protects against invalid values which still have non-zero probability to appear.

Finally, I decided it might be still useful to provide opportunity to convert private key only to uniform representation and back.

**Comment by ypopovych** [comment]
Yeah. From an API perspective, I think it's simpler to add a method for converting the full keychain to the uniform and back to the ed25519 form. And constructors for keychain so it can be created from both PKs. It's a good question do we need the PrivateKey Swift struct or not.

**Comment by ypopovych** [comment]
I want to avoid a lot of changes to the C part (though `key[31] &= 0b01111111;` can be added, I think we can try to create PR to the original C library, and check it there with library developer)

**Comment by ERussel** [comment]
Ok, I agree that we don't need PrivateKey struct in current approach with Keypair struct. Regarding `key[31] &= 0b01111111;` I opened an issue in the repo with original C implementation. Let's  see what will be the answer and then probably I could work on PR adding conversion from and to uniform representation for Keypair struct.

**Pull request closed without merging**
